// Game Industry ATS System Pack for Git-a-Job
// Created: 2026-03-26

export const GAME_ROLES_KEYWORDS = {
  "version": "2026-03-26",
  "createdFor": "Git-a-Job",
  "notes": [
    "High-recall game-industry ATS keyword bank.",
    "Designed for role detection, weighted scoring, and missing-term suggestions.",
    "Calibrated using current public game-studio and game-job-board role language, then expanded and curated for production use."
  ],
  "roles": {
    "qa_tester": {
      "displayName": "QA Tester",
      "roleFamily": "quality",
      "weights": {
        "coreTitles": 5.0,
        "altTitles": 4.0,
        "gameSignals": 4.5,
        "toolsAndTech": 3.5,
        "enginesPlatforms": 3.5,
        "methodologies": 3.0,
        "deliverables": 3.0,
        "outcomes": 3.0,
        "softSignals": 1.5
      },
      "categories": {
        "coreTitles": [
          "QA Tester",
          "Game Tester",
          "Quality Assurance Tester",
          "Game QA Tester",
          "Video Game Tester",
          "Gameplay Tester",
          "Software QA Tester",
          "QA Analyst",
          "Game QA Analyst",
          "Quality Assurance Analyst"
        ],
        "altTitles": [
          "Test Associate",
          "Test Specialist",
          "Test Technician",
          "Functional Tester",
          "Manual Tester",
          "Compatibility Tester",
          "Localization Tester",
          "Compliance Tester",
          "Certification Tester",
          "Live Ops Tester",
          "QA Associate",
          "QA Specialist",
          "Software Tester",
          "Console Tester",
          "Mobile QA Tester"
        ],
        "gameSignals": [
          "Game Testing",
          "Gameplay Testing",
          "Quest Testing",
          "Mission Testing",
          "Level Testing",
          "Progression Testing",
          "Economy Testing",
          "Monetization Testing",
          "Store Testing",
          "DLC Testing",
          "Patch Testing",
          "Hotfix Validation",
          "Live Ops Testing",
          "Event Testing",
          "Save/Load Testing",
          "Controller Testing",
          "Input Testing",
          "HUD Testing",
          "UI Testing",
          "UX Testing",
          "Audio Testing",
          "Localization Testing",
          "Translation Verification",
          "LQA",
          "Balance Testing",
          "Meta Testing",
          "Combat Testing",
          "Multiplayer Testing",
          "Matchmaking Testing",
          "Cross-Platform Testing",
          "Platform Certification",
          "Submission Readiness",
          "TRC",
          "TCR",
          "XR",
          "Lotcheck",
          "Compliance",
          "First-Party Requirements",
          "Console QA",
          "PC QA",
          "Mobile QA",
          "Free-to-Play",
          "F2P"
        ],
        "toolsAndTech": [
          "JIRA",
          "Azure DevOps",
          "TestRail",
          "Confluence",
          "Mantis",
          "Bugzilla",
          "Hansoft",
          "ShotGrid",
          "Excel",
          "Google Sheets",
          "Slack",
          "Discord",
          "Dev Kits",
          "Crash Dumps",
          "Debug Logs",
          "Log Analysis",
          "Screen Capture",
          "Video Capture",
          "Packet Capture",
          "Repro Steps",
          "Database Checks",
          "SQL Basics"
        ],
        "enginesPlatforms": [
          "Unity",
          "Unreal Engine",
          "PC",
          "Steam",
          "Epic Games Store",
          "PlayStation",
          "PS4",
          "PS5",
          "Xbox One",
          "Xbox Series X|S",
          "Nintendo Switch",
          "iOS",
          "Android",
          "Windows",
          "macOS"
        ],
        "methodologies": [
          "Functional Testing",
          "Regression Testing",
          "Smoke Testing",
          "Sanity Testing",
          "Exploratory Testing",
          "Black Box Testing",
          "White Box Testing",
          "Compatibility Testing",
          "Usability Testing",
          "Acceptance Testing",
          "User Acceptance Testing",
          "UAT",
          "Risk-Based Testing",
          "Agile",
          "Scrum",
          "Kanban",
          "Sprint Testing",
          "Daily Standups",
          "Bug Triage",
          "Issue Triage",
          "Severity",
          "Priority",
          "Verification",
          "Validation"
        ],
        "deliverables": [
          "Test Cases",
          "Test Plans",
          "Test Suites",
          "Checklists",
          "Bug Reports",
          "Defect Reports",
          "Daily Reports",
          "Pass/Fail Reporting",
          "Release Readiness Reports",
          "Test Metrics",
          "Coverage Reports",
          "Repro Videos",
          "Known Issues Lists",
          "Submission Checklists",
          "Patch Sign-Off",
          "Go/No-Go Input"
        ],
        "outcomes": [
          "Release Readiness",
          "Bug Prevention",
          "Defect Detection",
          "Quality Bar",
          "Player Experience",
          "Stability",
          "Crash Reduction",
          "Submission Success",
          "Regression Coverage",
          "Platform Compliance",
          "Repro Rate",
          "Issue Escalation",
          "Build Health",
          "Content Verification",
          "Risk Reduction"
        ],
        "softSignals": [
          "Attention to Detail",
          "Communication",
          "Collaboration",
          "Time Management",
          "Prioritization",
          "Documentation",
          "Problem Solving",
          "Ownership",
          "Accountability",
          "Adaptability",
          "Organization",
          "Escalation",
          "Follow-Through",
          "Critical Thinking",
          "Reliability"
        ]
      },
      "allTerms": [
        "QA Tester",
        "Game Tester",
        "Quality Assurance Tester",
        "Game QA Tester",
        "Video Game Tester",
        "Gameplay Tester",
        "Software QA Tester",
        "QA Analyst",
        "Game QA Analyst",
        "Quality Assurance Analyst",
        "Test Associate",
        "Test Specialist",
        "Test Technician",
        "Functional Tester",
        "Manual Tester",
        "Compatibility Tester",
        "Localization Tester",
        "Compliance Tester",
        "Certification Tester",
        "Live Ops Tester",
        "QA Associate",
        "QA Specialist",
        "Software Tester",
        "Console Tester",
        "Mobile QA Tester",
        "Game Testing",
        "Gameplay Testing",
        "Quest Testing",
        "Mission Testing",
        "Level Testing",
        "Progression Testing",
        "Economy Testing",
        "Monetization Testing",
        "Store Testing",
        "DLC Testing",
        "Patch Testing",
        "Hotfix Validation",
        "Live Ops Testing",
        "Event Testing",
        "Save/Load Testing",
        "Controller Testing",
        "Input Testing",
        "HUD Testing",
        "UI Testing",
        "UX Testing",
        "Audio Testing",
        "Localization Testing",
        "Translation Verification",
        "LQA",
        "Balance Testing",
        "Meta Testing",
        "Combat Testing",
        "Multiplayer Testing",
        "Matchmaking Testing",
        "Cross-Platform Testing",
        "Platform Certification",
        "Submission Readiness",
        "TRC",
        "TCR",
        "XR",
        "Lotcheck",
        "Compliance",
        "First-Party Requirements",
        "Console QA",
        "PC QA",
        "Mobile QA",
        "Free-to-Play",
        "F2P",
        "JIRA",
        "Azure DevOps",
        "TestRail",
        "Confluence",
        "Mantis",
        "Bugzilla",
        "Hansoft",
        "ShotGrid",
        "Excel",
        "Google Sheets",
        "Slack",
        "Discord",
        "Dev Kits",
        "Crash Dumps",
        "Debug Logs",
        "Log Analysis",
        "Screen Capture",
        "Video Capture",
        "Packet Capture",
        "Repro Steps",
        "Database Checks",
        "SQL Basics",
        "Unity",
        "Unreal Engine",
        "PC",
        "Steam",
        "Epic Games Store",
        "PlayStation",
        "PS4",
        "PS5",
        "Xbox One",
        "Xbox Series X|S",
        "Nintendo Switch",
        "iOS",
        "Android",
        "Windows",
        "macOS",
        "Functional Testing",
        "Regression Testing",
        "Smoke Testing",
        "Sanity Testing",
        "Exploratory Testing",
        "Black Box Testing",
        "White Box Testing",
        "Compatibility Testing",
        "Usability Testing",
        "Acceptance Testing",
        "User Acceptance Testing",
        "UAT",
        "Risk-Based Testing",
        "Agile",
        "Scrum",
        "Kanban",
        "Sprint Testing",
        "Daily Standups",
        "Bug Triage",
        "Issue Triage",
        "Severity",
        "Priority",
        "Verification",
        "Validation",
        "Test Cases",
        "Test Plans",
        "Test Suites",
        "Checklists",
        "Bug Reports",
        "Defect Reports",
        "Daily Reports",
        "Pass/Fail Reporting",
        "Release Readiness Reports",
        "Test Metrics",
        "Coverage Reports",
        "Repro Videos",
        "Known Issues Lists",
        "Submission Checklists",
        "Patch Sign-Off",
        "Go/No-Go Input",
        "Release Readiness",
        "Bug Prevention",
        "Defect Detection",
        "Quality Bar",
        "Player Experience",
        "Stability",
        "Crash Reduction",
        "Submission Success",
        "Regression Coverage",
        "Platform Compliance",
        "Repro Rate",
        "Issue Escalation",
        "Build Health",
        "Content Verification",
        "Risk Reduction",
        "Attention to Detail",
        "Communication",
        "Collaboration",
        "Time Management",
        "Prioritization",
        "Documentation",
        "Problem Solving",
        "Ownership",
        "Accountability",
        "Adaptability",
        "Organization",
        "Escalation",
        "Follow-Through",
        "Critical Thinking",
        "Reliability"
      ],
      "totalTerms": 175
    },
    "qa_lead": {
      "displayName": "QA Lead",
      "roleFamily": "quality",
      "weights": {
        "coreTitles": 5.0,
        "altTitles": 4.5,
        "gameSignals": 4.5,
        "toolsAndTech": 3.5,
        "enginesPlatforms": 3.0,
        "methodologies": 4.0,
        "deliverables": 4.0,
        "outcomes": 4.0,
        "softSignals": 2.0
      },
      "categories": {
        "coreTitles": [
          "QA Lead",
          "Lead QA",
          "Lead Quality Assurance",
          "Game QA Lead",
          "Quality Assurance Lead",
          "QA Team Lead",
          "Lead Tester",
          "Test Lead",
          "Lead QA Analyst",
          "Lead Game Tester"
        ],
        "altTitles": [
          "QA Supervisor",
          "QA Manager",
          "Senior QA Lead",
          "Certification Lead",
          "Compliance Lead",
          "Live QA Lead",
          "Embedded QA Lead",
          "Feature QA Lead",
          "Project QA Lead",
          "QA Coordinator"
        ],
        "gameSignals": [
          "Console Certification",
          "TRC",
          "TCR",
          "XR",
          "Lotcheck",
          "Submission Planning",
          "Submission Readiness",
          "Live Ops QA",
          "Patch Validation",
          "DLC Validation",
          "Event Validation",
          "Monetization QA",
          "Free-to-Play QA",
          "Cross-Platform QA",
          "Gameplay Coverage",
          "Quest Coverage",
          "Economy Coverage",
          "Localization Coverage",
          "Accessibility Testing",
          "First-Party Compliance",
          "Co-Dev QA",
          "External QA",
          "Outsourced QA",
          "Player Experience",
          "Shipped Titles",
          "Release Candidate Review",
          "Build Health"
        ],
        "toolsAndTech": [
          "JIRA",
          "Azure DevOps",
          "TestRail",
          "Confluence",
          "Power BI",
          "Excel",
          "Google Sheets",
          "SQL",
          "Dashboards",
          "Bug Databases",
          "Dev Kits",
          "Crash Reporting",
          "Telemetry Dashboards",
          "Miro",
          "Notion",
          "Slack",
          "Teams",
          "Hansoft",
          "ShotGrid",
          "Defect Tracking Systems"
        ],
        "enginesPlatforms": [
          "Unity",
          "Unreal Engine",
          "PC",
          "Steam",
          "PlayStation",
          "Xbox",
          "Nintendo Switch",
          "iOS",
          "Android"
        ],
        "methodologies": [
          "Test Strategy",
          "QA Strategy",
          "Test Planning",
          "Risk-Based Testing",
          "Regression Planning",
          "Smoke Testing",
          "Functional Testing",
          "Performance Testing",
          "Compatibility Testing",
          "Automation Strategy",
          "Agile",
          "Scrum",
          "Kanban",
          "Sprint Planning",
          "Capacity Planning",
          "Resource Planning",
          "Workload Balancing",
          "Bug Triage",
          "Issue Triage",
          "Defect Lifecycle",
          "Root Cause Analysis",
          "RCA",
          "Postmortem",
          "Retrospectives",
          "Continuous Improvement",
          "Process Improvement",
          "Quality Gates",
          "Go/No-Go"
        ],
        "deliverables": [
          "Test Plans",
          "Test Schedules",
          "Coverage Matrices",
          "Sign-Offs",
          "Release Recommendations",
          "Go/No-Go Recommendations",
          "Bug Triage Notes",
          "Status Reports",
          "Metrics Dashboards",
          "Risk Registers",
          "Test Estimates",
          "Hiring Plans",
          "Onboarding Plans",
          "Vendor Briefs",
          "Submission Checklists",
          "Escalation Summaries",
          "Team Goals",
          "QA Standards",
          "Best Practices"
        ],
        "outcomes": [
          "Release Readiness",
          "Quality Bar",
          "Risk Mitigation",
          "Defect Prevention",
          "Team Efficiency",
          "Coverage Expansion",
          "Stability Improvement",
          "Submission Success",
          "Launch Quality",
          "Player Satisfaction",
          "Process Scalability",
          "Reduced Escapes",
          "Improved Repro Quality",
          "Clear Prioritization",
          "Cross-Team Alignment"
        ],
        "softSignals": [
          "Leadership",
          "Mentorship",
          "Coaching",
          "Hiring",
          "Interviewing",
          "Performance Reviews",
          "Decision Making",
          "Conflict Resolution",
          "Communication",
          "Stakeholder Management",
          "Cross-Functional Collaboration",
          "Prioritization",
          "Execution",
          "Ownership",
          "Accountability",
          "Organization",
          "Presentation Skills",
          "Escalation Management",
          "Influence",
          "Team Alignment"
        ]
      },
      "allTerms": [
        "QA Lead",
        "Lead QA",
        "Lead Quality Assurance",
        "Game QA Lead",
        "Quality Assurance Lead",
        "QA Team Lead",
        "Lead Tester",
        "Test Lead",
        "Lead QA Analyst",
        "Lead Game Tester",
        "QA Supervisor",
        "QA Manager",
        "Senior QA Lead",
        "Certification Lead",
        "Compliance Lead",
        "Live QA Lead",
        "Embedded QA Lead",
        "Feature QA Lead",
        "Project QA Lead",
        "QA Coordinator",
        "Console Certification",
        "TRC",
        "TCR",
        "XR",
        "Lotcheck",
        "Submission Planning",
        "Submission Readiness",
        "Live Ops QA",
        "Patch Validation",
        "DLC Validation",
        "Event Validation",
        "Monetization QA",
        "Free-to-Play QA",
        "Cross-Platform QA",
        "Gameplay Coverage",
        "Quest Coverage",
        "Economy Coverage",
        "Localization Coverage",
        "Accessibility Testing",
        "First-Party Compliance",
        "Co-Dev QA",
        "External QA",
        "Outsourced QA",
        "Player Experience",
        "Shipped Titles",
        "Release Candidate Review",
        "Build Health",
        "JIRA",
        "Azure DevOps",
        "TestRail",
        "Confluence",
        "Power BI",
        "Excel",
        "Google Sheets",
        "SQL",
        "Dashboards",
        "Bug Databases",
        "Dev Kits",
        "Crash Reporting",
        "Telemetry Dashboards",
        "Miro",
        "Notion",
        "Slack",
        "Teams",
        "Hansoft",
        "ShotGrid",
        "Defect Tracking Systems",
        "Unity",
        "Unreal Engine",
        "PC",
        "Steam",
        "PlayStation",
        "Xbox",
        "Nintendo Switch",
        "iOS",
        "Android",
        "Test Strategy",
        "QA Strategy",
        "Test Planning",
        "Risk-Based Testing",
        "Regression Planning",
        "Smoke Testing",
        "Functional Testing",
        "Performance Testing",
        "Compatibility Testing",
        "Automation Strategy",
        "Agile",
        "Scrum",
        "Kanban",
        "Sprint Planning",
        "Capacity Planning",
        "Resource Planning",
        "Workload Balancing",
        "Bug Triage",
        "Issue Triage",
        "Defect Lifecycle",
        "Root Cause Analysis",
        "RCA",
        "Postmortem",
        "Retrospectives",
        "Continuous Improvement",
        "Process Improvement",
        "Quality Gates",
        "Go/No-Go",
        "Test Plans",
        "Test Schedules",
        "Coverage Matrices",
        "Sign-Offs",
        "Release Recommendations",
        "Go/No-Go Recommendations",
        "Bug Triage Notes",
        "Status Reports",
        "Metrics Dashboards",
        "Risk Registers",
        "Test Estimates",
        "Hiring Plans",
        "Onboarding Plans",
        "Vendor Briefs",
        "Submission Checklists",
        "Escalation Summaries",
        "Team Goals",
        "QA Standards",
        "Best Practices",
        "Release Readiness",
        "Quality Bar",
        "Risk Mitigation",
        "Defect Prevention",
        "Team Efficiency",
        "Coverage Expansion",
        "Stability Improvement",
        "Submission Success",
        "Launch Quality",
        "Player Satisfaction",
        "Process Scalability",
        "Reduced Escapes",
        "Improved Repro Quality",
        "Clear Prioritization",
        "Cross-Team Alignment",
        "Leadership",
        "Mentorship",
        "Coaching",
        "Hiring",
        "Interviewing",
        "Performance Reviews",
        "Decision Making",
        "Conflict Resolution",
        "Communication",
        "Stakeholder Management",
        "Cross-Functional Collaboration",
        "Prioritization",
        "Execution",
        "Ownership",
        "Accountability",
        "Organization",
        "Presentation Skills",
        "Escalation Management",
        "Influence",
        "Team Alignment"
      ],
      "totalTerms": 158
    },
    "qa_engineer": {
      "displayName": "QA Engineer",
      "roleFamily": "quality",
      "weights": {
        "coreTitles": 5.0,
        "altTitles": 4.5,
        "gameSignals": 4.0,
        "toolsAndTech": 5.0,
        "enginesPlatforms": 4.0,
        "methodologies": 4.0,
        "deliverables": 3.5,
        "outcomes": 3.5,
        "softSignals": 1.5
      },
      "categories": {
        "coreTitles": [
          "QA Engineer",
          "Game QA Engineer",
          "Quality Engineer",
          "Software QA Engineer",
          "SDET",
          "Software Development Engineer in Test",
          "Test Automation Engineer",
          "Automation QA Engineer",
          "Embedded QA Engineer",
          "Quality Assurance Engineer"
        ],
        "altTitles": [
          "Automation Engineer",
          "Test Engineer",
          "QA Automation Engineer",
          "Build Verification Engineer",
          "Release Validation Engineer",
          "Compliance Automation Engineer",
          "Performance Test Engineer",
          "Systems Test Engineer",
          "Tools QA Engineer",
          "Gameplay QA Engineer"
        ],
        "gameSignals": [
          "Gameplay Automation",
          "Client Validation",
          "Server Validation",
          "Multiplayer Validation",
          "Netcode Validation",
          "Live Ops Validation",
          "Patch Validation",
          "Hotfix Validation",
          "Store Validation",
          "Economy Validation",
          "Telemetry Validation",
          "Crash Analysis",
          "Frame Rate Validation",
          "Memory Validation",
          "Certification Automation",
          "TRC",
          "TCR",
          "XR",
          "Lotcheck",
          "Dev Kits",
          "Platform APIs",
          "Shipped Titles",
          "Build Farm",
          "Console Automation"
        ],
        "toolsAndTech": [
          "Selenium",
          "Playwright",
          "Cypress",
          "Appium",
          "Postman",
          "REST API",
          "GraphQL",
          "gRPC",
          "Python",
          "Java",
          "C#",
          "JavaScript",
          "TypeScript",
          "C++",
          "Bash",
          "PowerShell",
          "SQL",
          "NoSQL",
          "Git",
          "Perforce",
          "Jenkins",
          "GitHub Actions",
          "GitLab CI",
          "CI/CD",
          "Docker",
          "Kubernetes",
          "Test Harness",
          "Automation Framework",
          "Test Scripts",
          "SDK Testing",
          "Service Virtualization",
          "Mocking",
          "PyTest",
          "JUnit",
          "NUnit",
          "xUnit",
          "Unreal Automation Tool",
          "Unity Test Framework",
          "Device Farm",
          "BrowserStack",
          "Charles Proxy",
          "Wireshark",
          "Crash Dumps",
          "Log Parsing",
          "Observability"
        ],
        "enginesPlatforms": [
          "Unity",
          "Unreal Engine",
          "PC",
          "Windows",
          "Linux",
          "PlayStation",
          "Xbox",
          "Nintendo Switch",
          "iOS",
          "Android",
          "Steam",
          "Epic Games Store"
        ],
        "methodologies": [
          "API Testing",
          "Integration Testing",
          "End-to-End Testing",
          "E2E",
          "Unit Testing",
          "Regression Testing",
          "Smoke Testing",
          "Performance Testing",
          "Load Testing",
          "Stress Testing",
          "Soak Testing",
          "Compatibility Testing",
          "Continuous Testing",
          "Quality Gates",
          "Root Cause Analysis",
          "RCA",
          "Flaky Test Reduction",
          "Test Design",
          "Test Architecture",
          "Build Verification",
          "Agile",
          "Scrum",
          "Sprint Planning",
          "Defect Tracking",
          "Bug Reproduction"
        ],
        "deliverables": [
          "Automation Frameworks",
          "Regression Suites",
          "Smoke Suites",
          "Test Plans",
          "Test Cases",
          "Test Data",
          "Coverage Reports",
          "Pipeline Jobs",
          "Quality Dashboards",
          "Failure Triage Reports",
          "Release Sign-Off Input",
          "Tooling",
          "Shared Libraries",
          "CI Integrations",
          "Test Metrics",
          "Validation Reports"
        ],
        "outcomes": [
          "Scalability",
          "Maintainability",
          "Automation Reliability",
          "Reduced Manual Testing",
          "Faster Release Validation",
          "Improved Coverage",
          "Stability",
          "Defect Detection",
          "Lower Flake Rate",
          "Quality at Scale",
          "Build Confidence",
          "Release Readiness",
          "Performance Visibility",
          "Regression Prevention",
          "Faster Feedback"
        ],
        "softSignals": [
          "Problem Solving",
          "Communication",
          "Collaboration",
          "Ownership",
          "Documentation",
          "Critical Thinking",
          "Attention to Detail",
          "Execution",
          "Adaptability",
          "Cross-Functional Collaboration"
        ]
      },
      "allTerms": [
        "QA Engineer",
        "Game QA Engineer",
        "Quality Engineer",
        "Software QA Engineer",
        "SDET",
        "Software Development Engineer in Test",
        "Test Automation Engineer",
        "Automation QA Engineer",
        "Embedded QA Engineer",
        "Quality Assurance Engineer",
        "Automation Engineer",
        "Test Engineer",
        "QA Automation Engineer",
        "Build Verification Engineer",
        "Release Validation Engineer",
        "Compliance Automation Engineer",
        "Performance Test Engineer",
        "Systems Test Engineer",
        "Tools QA Engineer",
        "Gameplay QA Engineer",
        "Gameplay Automation",
        "Client Validation",
        "Server Validation",
        "Multiplayer Validation",
        "Netcode Validation",
        "Live Ops Validation",
        "Patch Validation",
        "Hotfix Validation",
        "Store Validation",
        "Economy Validation",
        "Telemetry Validation",
        "Crash Analysis",
        "Frame Rate Validation",
        "Memory Validation",
        "Certification Automation",
        "TRC",
        "TCR",
        "XR",
        "Lotcheck",
        "Dev Kits",
        "Platform APIs",
        "Shipped Titles",
        "Build Farm",
        "Console Automation",
        "Selenium",
        "Playwright",
        "Cypress",
        "Appium",
        "Postman",
        "REST API",
        "GraphQL",
        "gRPC",
        "Python",
        "Java",
        "C#",
        "JavaScript",
        "TypeScript",
        "C++",
        "Bash",
        "PowerShell",
        "SQL",
        "NoSQL",
        "Git",
        "Perforce",
        "Jenkins",
        "GitHub Actions",
        "GitLab CI",
        "CI/CD",
        "Docker",
        "Kubernetes",
        "Test Harness",
        "Automation Framework",
        "Test Scripts",
        "SDK Testing",
        "Service Virtualization",
        "Mocking",
        "PyTest",
        "JUnit",
        "NUnit",
        "xUnit",
        "Unreal Automation Tool",
        "Unity Test Framework",
        "Device Farm",
        "BrowserStack",
        "Charles Proxy",
        "Wireshark",
        "Crash Dumps",
        "Log Parsing",
        "Observability",
        "Unity",
        "Unreal Engine",
        "PC",
        "Windows",
        "Linux",
        "PlayStation",
        "Xbox",
        "Nintendo Switch",
        "iOS",
        "Android",
        "Steam",
        "Epic Games Store",
        "API Testing",
        "Integration Testing",
        "End-to-End Testing",
        "E2E",
        "Unit Testing",
        "Regression Testing",
        "Smoke Testing",
        "Performance Testing",
        "Load Testing",
        "Stress Testing",
        "Soak Testing",
        "Compatibility Testing",
        "Continuous Testing",
        "Quality Gates",
        "Root Cause Analysis",
        "RCA",
        "Flaky Test Reduction",
        "Test Design",
        "Test Architecture",
        "Build Verification",
        "Agile",
        "Scrum",
        "Sprint Planning",
        "Defect Tracking",
        "Bug Reproduction",
        "Automation Frameworks",
        "Regression Suites",
        "Smoke Suites",
        "Test Plans",
        "Test Cases",
        "Test Data",
        "Coverage Reports",
        "Pipeline Jobs",
        "Quality Dashboards",
        "Failure Triage Reports",
        "Release Sign-Off Input",
        "Tooling",
        "Shared Libraries",
        "CI Integrations",
        "Test Metrics",
        "Validation Reports",
        "Scalability",
        "Maintainability",
        "Automation Reliability",
        "Reduced Manual Testing",
        "Faster Release Validation",
        "Improved Coverage",
        "Stability",
        "Defect Detection",
        "Lower Flake Rate",
        "Quality at Scale",
        "Build Confidence",
        "Release Readiness",
        "Performance Visibility",
        "Regression Prevention",
        "Faster Feedback",
        "Problem Solving",
        "Communication",
        "Collaboration",
        "Ownership",
        "Documentation",
        "Critical Thinking",
        "Attention to Detail",
        "Execution",
        "Adaptability",
        "Cross-Functional Collaboration"
      ],
      "totalTerms": 167
    },
    "game_developer": {
      "displayName": "Game Developer",
      "roleFamily": "engineering",
      "weights": {
        "coreTitles": 5.0,
        "altTitles": 4.0,
        "gameSignals": 5.0,
        "toolsAndTech": 4.5,
        "enginesPlatforms": 4.5,
        "methodologies": 3.5,
        "deliverables": 3.5,
        "outcomes": 3.5,
        "softSignals": 1.5
      },
      "categories": {
        "coreTitles": [
          "Game Developer",
          "Gameplay Developer",
          "Gameplay Programmer",
          "Game Programmer",
          "Video Game Developer",
          "Game Engineer",
          "Systems Programmer",
          "Gameplay Engineer",
          "Game Systems Developer",
          "Game Software Developer"
        ],
        "altTitles": [
          "Core Gameplay Programmer",
          "Feature Programmer",
          "Engine Programmer",
          "AI Programmer",
          "Tools Programmer",
          "UI Programmer",
          "Technical Gameplay Designer",
          "Combat Programmer",
          "Systems Developer",
          "Game Logic Programmer"
        ],
        "gameSignals": [
          "Gameplay Systems",
          "Player Controller",
          "3Cs",
          "Character Controller",
          "Camera",
          "Combat Systems",
          "AI Systems",
          "Pathfinding",
          "Behavior Trees",
          "State Machines",
          "Input Systems",
          "Inventory Systems",
          "Quest Systems",
          "Mission Systems",
          "Dialogue Systems",
          "Save Systems",
          "Serialization",
          "Animation Systems",
          "Physics Gameplay",
          "Collision",
          "Ability Systems",
          "Skill Trees",
          "Progression Systems",
          "Economy Systems",
          "Crafting Systems",
          "UI Flow",
          "HUD",
          "Menus",
          "Meta Systems",
          "Live Ops Support",
          "DLC Support",
          "Patch Support",
          "Shipped Titles",
          "Rapid Prototyping",
          "Game Feel",
          "Balance Tuning",
          "Player Experience",
          "Moment-to-Moment Gameplay",
          "Core Loop",
          "Multiplayer Gameplay",
          "Replication",
          "Netcode",
          "Latency Compensation",
          "Anti-Cheat Awareness"
        ],
        "toolsAndTech": [
          "C++",
          "C#",
          "Python",
          "Lua",
          "JavaScript",
          "TypeScript",
          "Blueprints",
          "Visual Scripting",
          "Git",
          "Perforce",
          "Jenkins",
          "GitHub Actions",
          "CI/CD",
          "Profiling",
          "Debugging",
          "Memory Optimization",
          "CPU Optimization",
          "GPU Optimization",
          "Multithreading",
          "Concurrency",
          "Data-Oriented Design",
          "Design Patterns",
          "SOLID",
          "Code Reviews",
          "Refactoring",
          "Unit Testing",
          "Integration Testing",
          "Build Systems",
          "Editor Tools",
          "Tooling",
          "Scripting",
          "Shader Basics",
          "Rendering",
          "VFX Integration",
          "Audio Integration",
          "Telemetry",
          "Analytics Integration",
          "Crash Triage",
          "Performance Budgets",
          "Frame Time",
          "Memory Budgets",
          "Hot Reload"
        ],
        "enginesPlatforms": [
          "Unreal Engine",
          "Unity",
          "Custom Engine",
          "Windows",
          "Linux",
          "PlayStation",
          "PS5",
          "Xbox Series X|S",
          "Nintendo Switch",
          "iOS",
          "Android",
          "Steam",
          "Epic Games Store",
          "Console Development",
          "PC Development",
          "Mobile Development"
        ],
        "methodologies": [
          "Agile",
          "Scrum",
          "Sprint Planning",
          "Technical Design",
          "Software Architecture",
          "Feature Ownership",
          "Cross-Functional Collaboration",
          "Production Pipelines",
          "Content Pipelines",
          "Asset Integration",
          "Optimization Passes",
          "Bug Fixing",
          "Technical Debt Management",
          "Source Control",
          "Documentation",
          "Milestone Delivery",
          "Playtesting",
          "Iterative Development",
          "Build Stability"
        ],
        "deliverables": [
          "Gameplay Features",
          "Prototypes",
          "Technical Designs",
          "Tools",
          "Systems Documentation",
          "Feature Specs",
          "Debug Builds",
          "Performance Reports",
          "Release Fixes",
          "Pipeline Improvements",
          "Content Hooks",
          "Reusable Components",
          "Gameplay Metrics Hooks",
          "Submission Fixes"
        ],
        "outcomes": [
          "Performance Optimization",
          "Stable Builds",
          "Maintainability",
          "Scalability",
          "Faster Iteration",
          "Feature Delivery",
          "Reduced Bugs",
          "Better Feel",
          "Launch Readiness",
          "Optimized Memory",
          "Improved Frame Rate",
          "Cleaner Architecture",
          "Team Velocity",
          "Content Throughput"
        ],
        "softSignals": [
          "Problem Solving",
          "Communication",
          "Collaboration",
          "Ownership",
          "Execution",
          "Adaptability",
          "Creativity",
          "Attention to Detail",
          "Mentoring",
          "Learning Mindset"
        ]
      },
      "allTerms": [
        "Game Developer",
        "Gameplay Developer",
        "Gameplay Programmer",
        "Game Programmer",
        "Video Game Developer",
        "Game Engineer",
        "Systems Programmer",
        "Gameplay Engineer",
        "Game Systems Developer",
        "Game Software Developer",
        "Core Gameplay Programmer",
        "Feature Programmer",
        "Engine Programmer",
        "AI Programmer",
        "Tools Programmer",
        "UI Programmer",
        "Technical Gameplay Designer",
        "Combat Programmer",
        "Systems Developer",
        "Game Logic Programmer",
        "Gameplay Systems",
        "Player Controller",
        "3Cs",
        "Character Controller",
        "Camera",
        "Combat Systems",
        "AI Systems",
        "Pathfinding",
        "Behavior Trees",
        "State Machines",
        "Input Systems",
        "Inventory Systems",
        "Quest Systems",
        "Mission Systems",
        "Dialogue Systems",
        "Save Systems",
        "Serialization",
        "Animation Systems",
        "Physics Gameplay",
        "Collision",
        "Ability Systems",
        "Skill Trees",
        "Progression Systems",
        "Economy Systems",
        "Crafting Systems",
        "UI Flow",
        "HUD",
        "Menus",
        "Meta Systems",
        "Live Ops Support",
        "DLC Support",
        "Patch Support",
        "Shipped Titles",
        "Rapid Prototyping",
        "Game Feel",
        "Balance Tuning",
        "Player Experience",
        "Moment-to-Moment Gameplay",
        "Core Loop",
        "Multiplayer Gameplay",
        "Replication",
        "Netcode",
        "Latency Compensation",
        "Anti-Cheat Awareness",
        "C++",
        "C#",
        "Python",
        "Lua",
        "JavaScript",
        "TypeScript",
        "Blueprints",
        "Visual Scripting",
        "Git",
        "Perforce",
        "Jenkins",
        "GitHub Actions",
        "CI/CD",
        "Profiling",
        "Debugging",
        "Memory Optimization",
        "CPU Optimization",
        "GPU Optimization",
        "Multithreading",
        "Concurrency",
        "Data-Oriented Design",
        "Design Patterns",
        "SOLID",
        "Code Reviews",
        "Refactoring",
        "Unit Testing",
        "Integration Testing",
        "Build Systems",
        "Editor Tools",
        "Tooling",
        "Scripting",
        "Shader Basics",
        "Rendering",
        "VFX Integration",
        "Audio Integration",
        "Telemetry",
        "Analytics Integration",
        "Crash Triage",
        "Performance Budgets",
        "Frame Time",
        "Memory Budgets",
        "Hot Reload",
        "Unreal Engine",
        "Unity",
        "Custom Engine",
        "Windows",
        "Linux",
        "PlayStation",
        "PS5",
        "Xbox Series X|S",
        "Nintendo Switch",
        "iOS",
        "Android",
        "Steam",
        "Epic Games Store",
        "Console Development",
        "PC Development",
        "Mobile Development",
        "Agile",
        "Scrum",
        "Sprint Planning",
        "Technical Design",
        "Software Architecture",
        "Feature Ownership",
        "Cross-Functional Collaboration",
        "Production Pipelines",
        "Content Pipelines",
        "Asset Integration",
        "Optimization Passes",
        "Bug Fixing",
        "Technical Debt Management",
        "Source Control",
        "Documentation",
        "Milestone Delivery",
        "Playtesting",
        "Iterative Development",
        "Build Stability",
        "Gameplay Features",
        "Prototypes",
        "Technical Designs",
        "Tools",
        "Systems Documentation",
        "Feature Specs",
        "Debug Builds",
        "Performance Reports",
        "Release Fixes",
        "Pipeline Improvements",
        "Content Hooks",
        "Reusable Components",
        "Gameplay Metrics Hooks",
        "Submission Fixes",
        "Performance Optimization",
        "Stable Builds",
        "Maintainability",
        "Scalability",
        "Faster Iteration",
        "Feature Delivery",
        "Reduced Bugs",
        "Better Feel",
        "Launch Readiness",
        "Optimized Memory",
        "Improved Frame Rate",
        "Cleaner Architecture",
        "Team Velocity",
        "Content Throughput",
        "Problem Solving",
        "Communication",
        "Collaboration",
        "Ownership",
        "Execution",
        "Adaptability",
        "Creativity",
        "Attention to Detail",
        "Mentoring",
        "Learning Mindset"
      ],
      "totalTerms": 179
    },
    "software_engineer_game": {
      "displayName": "Software Engineer (Game Industry)",
      "roleFamily": "engineering",
      "weights": {
        "coreTitles": 5.0,
        "altTitles": 4.0,
        "gameSignals": 4.5,
        "toolsAndTech": 5.0,
        "enginesPlatforms": 3.5,
        "methodologies": 4.0,
        "deliverables": 3.5,
        "outcomes": 4.0,
        "softSignals": 1.5
      },
      "categories": {
        "coreTitles": [
          "Software Engineer",
          "Backend Engineer",
          "Full Stack Engineer",
          "Services Engineer",
          "Platform Engineer",
          "Online Systems Engineer",
          "Game Services Engineer",
          "Game Backend Engineer",
          "Systems Engineer",
          "Application Engineer"
        ],
        "altTitles": [
          "Software Developer",
          "Backend Developer",
          "Full Stack Developer",
          "Server Engineer",
          "Cloud Engineer",
          "Release Engineer",
          "Developer Experience Engineer",
          "Site Reliability Engineer",
          "SRE",
          "Infrastructure Engineer"
        ],
        "gameSignals": [
          "Game Services",
          "Online Services",
          "Player Account Systems",
          "Authentication",
          "Authorization",
          "Identity",
          "Commerce",
          "Payments",
          "Entitlements",
          "Inventory Systems",
          "Matchmaking",
          "Leaderboards",
          "Friends Systems",
          "Chat Services",
          "Presence",
          "Game Telemetry",
          "Live Ops",
          "Live Services",
          "Patch Delivery",
          "CDN",
          "Content Distribution",
          "Anti-Cheat Services",
          "Session Services",
          "Lobby Services",
          "Cross-Play",
          "Cross-Progression",
          "Shipped Titles",
          "Launch Support",
          "Incident Response",
          "On-Call",
          "Release Engineering",
          "Developer Experience"
        ],
        "toolsAndTech": [
          "C#",
          "Java",
          "Go",
          "Python",
          "Node.js",
          "JavaScript",
          "TypeScript",
          "C++",
          "SQL",
          "NoSQL",
          "PostgreSQL",
          "MySQL",
          "Redis",
          "MongoDB",
          "Cassandra",
          "Kafka",
          "RabbitMQ",
          "gRPC",
          "REST",
          "GraphQL",
          "Docker",
          "Kubernetes",
          "AWS",
          "GCP",
          "Azure",
          "Terraform",
          "CI/CD",
          "Jenkins",
          "GitHub Actions",
          "GitLab CI",
          "Git",
          "Perforce",
          "Observability",
          "Monitoring",
          "Logging",
          "Alerting",
          "Tracing",
          "Load Balancing",
          "Caching",
          "Microservices",
          "Event-Driven Architecture",
          "Distributed Systems",
          "System Design",
          "API Design",
          "Security",
          "OAuth",
          "SAML",
          "Cloud Storage",
          "Helm",
          "Linux",
          "Unix",
          "Bash",
          "Performance Tuning",
          "Scalability"
        ],
        "enginesPlatforms": [
          "PlayStation",
          "Xbox",
          "Nintendo Switch",
          "Steam",
          "Epic Games Store",
          "PC",
          "Mobile",
          "Console"
        ],
        "methodologies": [
          "Agile",
          "Scrum",
          "Kanban",
          "Code Reviews",
          "Testing",
          "Unit Tests",
          "Integration Tests",
          "E2E Tests",
          "Release Management",
          "Incident Management",
          "SLA",
          "SLO",
          "Root Cause Analysis",
          "RCA",
          "Architecture Reviews",
          "Documentation",
          "Ownership",
          "Cross-Functional Collaboration",
          "Security Reviews",
          "Reliability Engineering"
        ],
        "deliverables": [
          "APIs",
          "Backend Systems",
          "Developer Tools",
          "Build Pipelines",
          "Monitoring Dashboards",
          "Operational Runbooks",
          "Release Notes",
          "Architecture Docs",
          "Load Test Reports",
          "Migration Plans",
          "Service Level Objectives",
          "Alert Policies",
          "Feature Flags",
          "Operational Playbooks"
        ],
        "outcomes": [
          "Reliability",
          "Availability",
          "Low Latency",
          "Resilience",
          "Operational Excellence",
          "Launch Stability",
          "Faster Deployments",
          "Better Developer Velocity",
          "Reduced Downtime",
          "Cost Efficiency",
          "Global Scale",
          "Player Trust",
          "Service Health"
        ],
        "softSignals": [
          "Problem Solving",
          "Communication",
          "Collaboration",
          "Execution",
          "Mentorship",
          "Design Thinking",
          "Trade-Offs",
          "Adaptability",
          "Customer Focus"
        ]
      },
      "allTerms": [
        "Software Engineer",
        "Backend Engineer",
        "Full Stack Engineer",
        "Services Engineer",
        "Platform Engineer",
        "Online Systems Engineer",
        "Game Services Engineer",
        "Game Backend Engineer",
        "Systems Engineer",
        "Application Engineer",
        "Software Developer",
        "Backend Developer",
        "Full Stack Developer",
        "Server Engineer",
        "Cloud Engineer",
        "Release Engineer",
        "Developer Experience Engineer",
        "Site Reliability Engineer",
        "SRE",
        "Infrastructure Engineer",
        "Game Services",
        "Online Services",
        "Player Account Systems",
        "Authentication",
        "Authorization",
        "Identity",
        "Commerce",
        "Payments",
        "Entitlements",
        "Inventory Systems",
        "Matchmaking",
        "Leaderboards",
        "Friends Systems",
        "Chat Services",
        "Presence",
        "Game Telemetry",
        "Live Ops",
        "Live Services",
        "Patch Delivery",
        "CDN",
        "Content Distribution",
        "Anti-Cheat Services",
        "Session Services",
        "Lobby Services",
        "Cross-Play",
        "Cross-Progression",
        "Shipped Titles",
        "Launch Support",
        "Incident Response",
        "On-Call",
        "Release Engineering",
        "Developer Experience",
        "C#",
        "Java",
        "Go",
        "Python",
        "Node.js",
        "JavaScript",
        "TypeScript",
        "C++",
        "SQL",
        "NoSQL",
        "PostgreSQL",
        "MySQL",
        "Redis",
        "MongoDB",
        "Cassandra",
        "Kafka",
        "RabbitMQ",
        "gRPC",
        "REST",
        "GraphQL",
        "Docker",
        "Kubernetes",
        "AWS",
        "GCP",
        "Azure",
        "Terraform",
        "CI/CD",
        "Jenkins",
        "GitHub Actions",
        "GitLab CI",
        "Git",
        "Perforce",
        "Observability",
        "Monitoring",
        "Logging",
        "Alerting",
        "Tracing",
        "Load Balancing",
        "Caching",
        "Microservices",
        "Event-Driven Architecture",
        "Distributed Systems",
        "System Design",
        "API Design",
        "Security",
        "OAuth",
        "SAML",
        "Cloud Storage",
        "Helm",
        "Linux",
        "Unix",
        "Bash",
        "Performance Tuning",
        "Scalability",
        "PlayStation",
        "Xbox",
        "Nintendo Switch",
        "Steam",
        "Epic Games Store",
        "PC",
        "Mobile",
        "Console",
        "Agile",
        "Scrum",
        "Kanban",
        "Code Reviews",
        "Testing",
        "Unit Tests",
        "Integration Tests",
        "E2E Tests",
        "Release Management",
        "Incident Management",
        "SLA",
        "SLO",
        "Root Cause Analysis",
        "RCA",
        "Architecture Reviews",
        "Documentation",
        "Ownership",
        "Cross-Functional Collaboration",
        "Security Reviews",
        "Reliability Engineering",
        "APIs",
        "Backend Systems",
        "Developer Tools",
        "Build Pipelines",
        "Monitoring Dashboards",
        "Operational Runbooks",
        "Release Notes",
        "Architecture Docs",
        "Load Test Reports",
        "Migration Plans",
        "Service Level Objectives",
        "Alert Policies",
        "Feature Flags",
        "Operational Playbooks",
        "Reliability",
        "Availability",
        "Low Latency",
        "Resilience",
        "Operational Excellence",
        "Launch Stability",
        "Faster Deployments",
        "Better Developer Velocity",
        "Reduced Downtime",
        "Cost Efficiency",
        "Global Scale",
        "Player Trust",
        "Service Health",
        "Problem Solving",
        "Communication",
        "Collaboration",
        "Execution",
        "Mentorship",
        "Design Thinking",
        "Trade-Offs",
        "Adaptability",
        "Customer Focus"
      ],
      "totalTerms": 170
    },
    "producer": {
      "displayName": "Producer",
      "roleFamily": "production",
      "weights": {
        "coreTitles": 5.0,
        "altTitles": 4.5,
        "gameSignals": 5.0,
        "toolsAndTech": 3.0,
        "enginesPlatforms": 2.0,
        "methodologies": 5.0,
        "deliverables": 4.5,
        "outcomes": 4.5,
        "softSignals": 2.5
      },
      "categories": {
        "coreTitles": [
          "Producer",
          "Game Producer",
          "Technical Producer",
          "Development Producer",
          "Associate Producer",
          "Senior Producer",
          "Live Producer",
          "Production Manager",
          "Project Manager",
          "Program Manager"
        ],
        "altTitles": [
          "Project Coordinator",
          "Development Manager",
          "Delivery Manager",
          "Project Lead",
          "Production Lead",
          "Feature Producer",
          "External Production Manager",
          "Co-Development Producer",
          "Operations Producer",
          "Release Producer"
        ],
        "gameSignals": [
          "Game Production",
          "AAA Development",
          "AA Development",
          "Co-Development",
          "External Development",
          "Outsourcing",
          "Milestones",
          "Vertical Slice",
          "Alpha",
          "Beta",
          "Gold Master",
          "Certification",
          "TRC",
          "TCR",
          "XR",
          "Lotcheck",
          "Submission Management",
          "Release Candidate",
          "Live Ops",
          "Seasonal Content",
          "DLC",
          "Patch Planning",
          "Event Planning",
          "Localization Coordination",
          "QA Coordination",
          "Shipped Titles",
          "Content Roadmap",
          "Playtest Coordination",
          "Player Experience",
          "Multi-Studio Development",
          "Cross-Disciplinary Teams"
        ],
        "toolsAndTech": [
          "JIRA",
          "Confluence",
          "Excel",
          "Google Sheets",
          "Smartsheet",
          "Asana",
          "Monday.com",
          "Notion",
          "Miro",
          "PowerPoint",
          "ShotGrid",
          "Hansoft",
          "Slack",
          "Teams",
          "Roadmaps",
          "Dashboards",
          "Status Reporting"
        ],
        "enginesPlatforms": [
          "Unity",
          "Unreal Engine",
          "PlayStation",
          "Xbox",
          "Nintendo Switch",
          "PC",
          "Mobile"
        ],
        "methodologies": [
          "Project Management",
          "Program Management",
          "Agile",
          "Scrum",
          "Kanban",
          "Sprint Planning",
          "Backlog Management",
          "Roadmapping",
          "Milestone Planning",
          "Schedule Management",
          "Dependency Management",
          "Risk Management",
          "Issue Tracking",
          "Escalation Management",
          "Resource Planning",
          "Capacity Planning",
          "Budget Management",
          "Forecasting",
          "Scope Management",
          "Change Management",
          "Go-to-Market Coordination",
          "Release Planning",
          "Go/No-Go",
          "Retrospectives",
          "Burndown",
          "Velocity",
          "OKRs",
          "Workflow Optimization"
        ],
        "deliverables": [
          "Schedules",
          "Milestone Plans",
          "Risk Registers",
          "Dependency Maps",
          "Status Reports",
          "Executive Updates",
          "Meeting Notes",
          "Action Item Trackers",
          "Launch Plans",
          "Release Checklists",
          "Communication Plans",
          "Team Goals",
          "Staffing Plans",
          "Postmortems",
          "Process Docs",
          "Partner Briefs"
        ],
        "outcomes": [
          "On-Time Delivery",
          "On-Budget Delivery",
          "Team Alignment",
          "Predictable Execution",
          "Risk Mitigation",
          "Roadblock Removal",
          "Cross-Team Coordination",
          "Launch Readiness",
          "Operational Excellence",
          "Content Throughput",
          "Quality Bar",
          "Stakeholder Confidence",
          "Clear Communication",
          "Healthy Production Rhythm",
          "Execution Discipline"
        ],
        "softSignals": [
          "Leadership",
          "Communication",
          "Facilitation",
          "Decision Making",
          "Conflict Resolution",
          "Prioritization",
          "Ownership",
          "Accountability",
          "Organization",
          "Collaboration",
          "Influence",
          "Follow-Through",
          "Problem Solving",
          "Adaptability",
          "Presentation Skills"
        ]
      },
      "allTerms": [
        "Producer",
        "Game Producer",
        "Technical Producer",
        "Development Producer",
        "Associate Producer",
        "Senior Producer",
        "Live Producer",
        "Production Manager",
        "Project Manager",
        "Program Manager",
        "Project Coordinator",
        "Development Manager",
        "Delivery Manager",
        "Project Lead",
        "Production Lead",
        "Feature Producer",
        "External Production Manager",
        "Co-Development Producer",
        "Operations Producer",
        "Release Producer",
        "Game Production",
        "AAA Development",
        "AA Development",
        "Co-Development",
        "External Development",
        "Outsourcing",
        "Milestones",
        "Vertical Slice",
        "Alpha",
        "Beta",
        "Gold Master",
        "Certification",
        "TRC",
        "TCR",
        "XR",
        "Lotcheck",
        "Submission Management",
        "Release Candidate",
        "Live Ops",
        "Seasonal Content",
        "DLC",
        "Patch Planning",
        "Event Planning",
        "Localization Coordination",
        "QA Coordination",
        "Shipped Titles",
        "Content Roadmap",
        "Playtest Coordination",
        "Player Experience",
        "Multi-Studio Development",
        "Cross-Disciplinary Teams",
        "JIRA",
        "Confluence",
        "Excel",
        "Google Sheets",
        "Smartsheet",
        "Asana",
        "Monday.com",
        "Notion",
        "Miro",
        "PowerPoint",
        "ShotGrid",
        "Hansoft",
        "Slack",
        "Teams",
        "Roadmaps",
        "Dashboards",
        "Status Reporting",
        "Unity",
        "Unreal Engine",
        "PlayStation",
        "Xbox",
        "Nintendo Switch",
        "PC",
        "Mobile",
        "Project Management",
        "Program Management",
        "Agile",
        "Scrum",
        "Kanban",
        "Sprint Planning",
        "Backlog Management",
        "Roadmapping",
        "Milestone Planning",
        "Schedule Management",
        "Dependency Management",
        "Risk Management",
        "Issue Tracking",
        "Escalation Management",
        "Resource Planning",
        "Capacity Planning",
        "Budget Management",
        "Forecasting",
        "Scope Management",
        "Change Management",
        "Go-to-Market Coordination",
        "Release Planning",
        "Go/No-Go",
        "Retrospectives",
        "Burndown",
        "Velocity",
        "OKRs",
        "Workflow Optimization",
        "Schedules",
        "Milestone Plans",
        "Risk Registers",
        "Dependency Maps",
        "Status Reports",
        "Executive Updates",
        "Meeting Notes",
        "Action Item Trackers",
        "Launch Plans",
        "Release Checklists",
        "Communication Plans",
        "Team Goals",
        "Staffing Plans",
        "Postmortems",
        "Process Docs",
        "Partner Briefs",
        "On-Time Delivery",
        "On-Budget Delivery",
        "Team Alignment",
        "Predictable Execution",
        "Risk Mitigation",
        "Roadblock Removal",
        "Cross-Team Coordination",
        "Launch Readiness",
        "Operational Excellence",
        "Content Throughput",
        "Quality Bar",
        "Stakeholder Confidence",
        "Clear Communication",
        "Healthy Production Rhythm",
        "Execution Discipline",
        "Leadership",
        "Communication",
        "Facilitation",
        "Decision Making",
        "Conflict Resolution",
        "Prioritization",
        "Ownership",
        "Accountability",
        "Organization",
        "Collaboration",
        "Influence",
        "Follow-Through",
        "Problem Solving",
        "Adaptability",
        "Presentation Skills"
      ],
      "totalTerms": 149
    },
    "product_owner": {
      "displayName": "Product Owner",
      "roleFamily": "product",
      "weights": {
        "coreTitles": 5.0,
        "altTitles": 4.5,
        "gameSignals": 5.0,
        "toolsAndTech": 3.5,
        "enginesPlatforms": 1.5,
        "methodologies": 5.0,
        "deliverables": 4.5,
        "outcomes": 5.0,
        "softSignals": 2.0
      },
      "categories": {
        "coreTitles": [
          "Product Owner",
          "Game Product Owner",
          "Product Manager",
          "Game Product Manager",
          "Live Product Manager",
          "Feature Owner",
          "Platform Product Owner",
          "Monetization Product Manager",
          "Growth Product Manager",
          "Product Lead"
        ],
        "altTitles": [
          "Associate Product Manager",
          "Senior Product Manager",
          "Technical Product Manager",
          "Live Ops Product Manager",
          "Economy Product Manager",
          "Player Experience Product Manager",
          "CRM Product Manager",
          "Content Product Manager",
          "Release Product Owner",
          "Scrum Product Owner"
        ],
        "gameSignals": [
          "Player Experience",
          "Engagement",
          "Retention",
          "Monetization",
          "F2P",
          "Live Ops",
          "In-Game Events",
          "Battle Pass",
          "Storefront",
          "Offers",
          "Bundles",
          "Pricing",
          "Economy Design",
          "Progression Design",
          "A/B Testing",
          "Experimentation",
          "Segmentation",
          "Cohort Analysis",
          "Churn",
          "LTV",
          "ARPU",
          "ARPPU",
          "DAU",
          "MAU",
          "WAU",
          "Feature Adoption",
          "Conversion",
          "Funnels",
          "Session Length",
          "Player Feedback",
          "Community Feedback",
          "Surveys",
          "Competitive Analysis",
          "Roadmap Alignment",
          "Release Planning",
          "Content Planning",
          "Launch Planning"
        ],
        "toolsAndTech": [
          "JIRA",
          "Confluence",
          "Amplitude",
          "Mixpanel",
          "Looker",
          "Tableau",
          "Power BI",
          "Google Analytics",
          "Excel",
          "SQL",
          "Airtable",
          "Miro",
          "Notion",
          "Optimizely",
          "Feature Flags",
          "Dashboards",
          "Telemetry",
          "Event Taxonomy"
        ],
        "enginesPlatforms": [
          "PC",
          "Console",
          "Mobile",
          "Free-to-Play",
          "Premium",
          "Cross-Platform"
        ],
        "methodologies": [
          "Backlog Management",
          "User Stories",
          "Acceptance Criteria",
          "Prioritization",
          "Roadmapping",
          "Product Strategy",
          "Product Vision",
          "Requirements Gathering",
          "Agile",
          "Scrum",
          "Kanban",
          "Sprint Planning",
          "Sprint Reviews",
          "Backlog Grooming",
          "Refinement",
          "MVP",
          "Hypothesis Testing",
          "Success Metrics",
          "Product Discovery",
          "Go-to-Market",
          "Stakeholder Management",
          "Risk Management",
          "Scope Management",
          "Outcome Ownership",
          "Value Delivery"
        ],
        "deliverables": [
          "Roadmaps",
          "PRDs",
          "Experiment Briefs",
          "Metric Trees",
          "Launch Plans",
          "Prioritization Frameworks",
          "Requirements Docs",
          "Competitive Audits",
          "Decision Logs",
          "Feature Specs",
          "Post-Launch Readouts",
          "Stakeholder Updates",
          "Opportunity Assessments"
        ],
        "outcomes": [
          "Revenue Growth",
          "Retention Lift",
          "Engagement Lift",
          "Conversion Improvement",
          "Reduced Churn",
          "Player Value",
          "Clear Prioritization",
          "Roadmap Clarity",
          "Feature-Market Fit",
          "Player Satisfaction",
          "Business Impact",
          "Validated Learning",
          "Faster Iteration",
          "Aligned Stakeholders",
          "Stronger Live Ops Performance"
        ],
        "softSignals": [
          "Communication",
          "Decision Making",
          "Trade-Offs",
          "Collaboration",
          "Player-Centric Thinking",
          "Analytical Thinking",
          "Ownership",
          "Influence",
          "Adaptability",
          "Execution",
          "Storytelling",
          "Stakeholder Alignment"
        ]
      },
      "allTerms": [
        "Product Owner",
        "Game Product Owner",
        "Product Manager",
        "Game Product Manager",
        "Live Product Manager",
        "Feature Owner",
        "Platform Product Owner",
        "Monetization Product Manager",
        "Growth Product Manager",
        "Product Lead",
        "Associate Product Manager",
        "Senior Product Manager",
        "Technical Product Manager",
        "Live Ops Product Manager",
        "Economy Product Manager",
        "Player Experience Product Manager",
        "CRM Product Manager",
        "Content Product Manager",
        "Release Product Owner",
        "Scrum Product Owner",
        "Player Experience",
        "Engagement",
        "Retention",
        "Monetization",
        "F2P",
        "Live Ops",
        "In-Game Events",
        "Battle Pass",
        "Storefront",
        "Offers",
        "Bundles",
        "Pricing",
        "Economy Design",
        "Progression Design",
        "A/B Testing",
        "Experimentation",
        "Segmentation",
        "Cohort Analysis",
        "Churn",
        "LTV",
        "ARPU",
        "ARPPU",
        "DAU",
        "MAU",
        "WAU",
        "Feature Adoption",
        "Conversion",
        "Funnels",
        "Session Length",
        "Player Feedback",
        "Community Feedback",
        "Surveys",
        "Competitive Analysis",
        "Roadmap Alignment",
        "Release Planning",
        "Content Planning",
        "Launch Planning",
        "JIRA",
        "Confluence",
        "Amplitude",
        "Mixpanel",
        "Looker",
        "Tableau",
        "Power BI",
        "Google Analytics",
        "Excel",
        "SQL",
        "Airtable",
        "Miro",
        "Notion",
        "Optimizely",
        "Feature Flags",
        "Dashboards",
        "Telemetry",
        "Event Taxonomy",
        "PC",
        "Console",
        "Mobile",
        "Free-to-Play",
        "Premium",
        "Cross-Platform",
        "Backlog Management",
        "User Stories",
        "Acceptance Criteria",
        "Prioritization",
        "Roadmapping",
        "Product Strategy",
        "Product Vision",
        "Requirements Gathering",
        "Agile",
        "Scrum",
        "Kanban",
        "Sprint Planning",
        "Sprint Reviews",
        "Backlog Grooming",
        "Refinement",
        "MVP",
        "Hypothesis Testing",
        "Success Metrics",
        "Product Discovery",
        "Go-to-Market",
        "Stakeholder Management",
        "Risk Management",
        "Scope Management",
        "Outcome Ownership",
        "Value Delivery",
        "Roadmaps",
        "PRDs",
        "Experiment Briefs",
        "Metric Trees",
        "Launch Plans",
        "Prioritization Frameworks",
        "Requirements Docs",
        "Competitive Audits",
        "Decision Logs",
        "Feature Specs",
        "Post-Launch Readouts",
        "Stakeholder Updates",
        "Opportunity Assessments",
        "Revenue Growth",
        "Retention Lift",
        "Engagement Lift",
        "Conversion Improvement",
        "Reduced Churn",
        "Player Value",
        "Clear Prioritization",
        "Roadmap Clarity",
        "Feature-Market Fit",
        "Player Satisfaction",
        "Business Impact",
        "Validated Learning",
        "Faster Iteration",
        "Aligned Stakeholders",
        "Stronger Live Ops Performance",
        "Communication",
        "Decision Making",
        "Trade-Offs",
        "Collaboration",
        "Player-Centric Thinking",
        "Analytical Thinking",
        "Ownership",
        "Influence",
        "Adaptability",
        "Execution",
        "Storytelling",
        "Stakeholder Alignment"
      ],
      "totalTerms": 146
    },
    "game_artist": {
      "displayName": "Game Artist",
      "roleFamily": "art",
      "weights": {
        "coreTitles": 5.0,
        "altTitles": 4.5,
        "gameSignals": 5.0,
        "toolsAndTech": 4.5,
        "enginesPlatforms": 3.5,
        "methodologies": 3.5,
        "deliverables": 4.0,
        "outcomes": 3.5,
        "softSignals": 2.0
      },
      "categories": {
        "coreTitles": [
          "Game Artist",
          "2D Artist",
          "3D Artist",
          "Concept Artist",
          "Character Artist",
          "Environment Artist",
          "UI Artist",
          "VFX Artist",
          "Prop Artist",
          "Illustrator"
        ],
        "altTitles": [
          "Visual Designer",
          "Technical Artist",
          "Lighting Artist",
          "Material Artist",
          "UI/UX Artist",
          "Creature Artist",
          "Animation Artist",
          "World Artist",
          "Weapon Artist",
          "Senior Artist"
        ],
        "gameSignals": [
          "Game Art",
          "Stylized Art",
          "Realistic Art",
          "Visual Development",
          "World Building",
          "Visual Storytelling",
          "Character Design",
          "Environment Design",
          "Prop Design",
          "Hard Surface",
          "Organic Modeling",
          "Creature Design",
          "Weapons",
          "Vehicles",
          "UI Mockups",
          "HUD Art",
          "Iconography",
          "Splash Art",
          "Marketing Key Art",
          "In-Engine Art",
          "Asset Integration",
          "Gameplay Readability",
          "Silhouette",
          "Shape Language",
          "Composition",
          "Color Theory",
          "PBR",
          "Material Definition",
          "Texture Budgets",
          "Polygon Budgets",
          "LODs",
          "Optimization",
          "Console Constraints",
          "Mobile Constraints",
          "Shipped Titles",
          "Art Bibles",
          "Style Guides",
          "Feedback Iteration"
        ],
        "toolsAndTech": [
          "Photoshop",
          "Figma",
          "Blender",
          "Maya",
          "3ds Max",
          "ZBrush",
          "Substance Painter",
          "Substance Designer",
          "After Effects",
          "Spine",
          "Aseprite",
          "Marmoset Toolbag",
          "Marvelous Designer",
          "RizomUV",
          "KeyShot",
          "ShotGrid",
          "Perforce",
          "Git",
          "JIRA",
          "Confluence",
          "Texture Atlasing",
          "UV Mapping",
          "Retopology",
          "Rigging",
          "Skinning",
          "Animation",
          "VFX",
          "Particles",
          "Shaders",
          "Lighting",
          "Rendering"
        ],
        "enginesPlatforms": [
          "Unity",
          "Unreal Engine",
          "PC",
          "Console",
          "Mobile",
          "AR/VR"
        ],
        "methodologies": [
          "Asset Pipeline",
          "Production Pipelines",
          "Reference Gathering",
          "Mood Boards",
          "Iteration",
          "Art Reviews",
          "Feedback Cycles",
          "Naming Conventions",
          "File Management",
          "Task Estimation",
          "Time Management",
          "Cross-Functional Collaboration",
          "Documentation",
          "Optimization Passes",
          "Import Pipelines",
          "Quality Bar"
        ],
        "deliverables": [
          "Concept Sheets",
          "Model Sheets",
          "Turnarounds",
          "Orthographics",
          "3D Assets",
          "Textures",
          "Materials",
          "UI Kits",
          "Icon Sets",
          "VFX Packages",
          "Presentation Decks",
          "In-Engine Scenes",
          "Look Dev",
          "Lighting Passes",
          "Polish Passes",
          "Portfolio Pieces"
        ],
        "outcomes": [
          "Visual Clarity",
          "Production Quality",
          "Readability",
          "Strong Art Direction",
          "Consistent Style",
          "Optimized Assets",
          "Faster Integration",
          "Player Immersion",
          "Clear Feedback",
          "High Visual Fidelity",
          "Efficient Pipeline",
          "Lower Rework",
          "Better Presentation",
          "Shippable Content",
          "Polish"
        ],
        "softSignals": [
          "Creativity",
          "Communication",
          "Collaboration",
          "Attention to Detail",
          "Ownership",
          "Adaptability",
          "Critique Handling",
          "Presentation Skills",
          "Problem Solving",
          "Organization",
          "Artistic Judgment",
          "Empathy"
        ]
      },
      "allTerms": [
        "Game Artist",
        "2D Artist",
        "3D Artist",
        "Concept Artist",
        "Character Artist",
        "Environment Artist",
        "UI Artist",
        "VFX Artist",
        "Prop Artist",
        "Illustrator",
        "Visual Designer",
        "Technical Artist",
        "Lighting Artist",
        "Material Artist",
        "UI/UX Artist",
        "Creature Artist",
        "Animation Artist",
        "World Artist",
        "Weapon Artist",
        "Senior Artist",
        "Game Art",
        "Stylized Art",
        "Realistic Art",
        "Visual Development",
        "World Building",
        "Visual Storytelling",
        "Character Design",
        "Environment Design",
        "Prop Design",
        "Hard Surface",
        "Organic Modeling",
        "Creature Design",
        "Weapons",
        "Vehicles",
        "UI Mockups",
        "HUD Art",
        "Iconography",
        "Splash Art",
        "Marketing Key Art",
        "In-Engine Art",
        "Asset Integration",
        "Gameplay Readability",
        "Silhouette",
        "Shape Language",
        "Composition",
        "Color Theory",
        "PBR",
        "Material Definition",
        "Texture Budgets",
        "Polygon Budgets",
        "LODs",
        "Optimization",
        "Console Constraints",
        "Mobile Constraints",
        "Shipped Titles",
        "Art Bibles",
        "Style Guides",
        "Feedback Iteration",
        "Photoshop",
        "Figma",
        "Blender",
        "Maya",
        "3ds Max",
        "ZBrush",
        "Substance Painter",
        "Substance Designer",
        "After Effects",
        "Spine",
        "Aseprite",
        "Marmoset Toolbag",
        "Marvelous Designer",
        "RizomUV",
        "KeyShot",
        "ShotGrid",
        "Perforce",
        "Git",
        "JIRA",
        "Confluence",
        "Texture Atlasing",
        "UV Mapping",
        "Retopology",
        "Rigging",
        "Skinning",
        "Animation",
        "VFX",
        "Particles",
        "Shaders",
        "Lighting",
        "Rendering",
        "Unity",
        "Unreal Engine",
        "PC",
        "Console",
        "Mobile",
        "AR/VR",
        "Asset Pipeline",
        "Production Pipelines",
        "Reference Gathering",
        "Mood Boards",
        "Iteration",
        "Art Reviews",
        "Feedback Cycles",
        "Naming Conventions",
        "File Management",
        "Task Estimation",
        "Time Management",
        "Cross-Functional Collaboration",
        "Documentation",
        "Optimization Passes",
        "Import Pipelines",
        "Quality Bar",
        "Concept Sheets",
        "Model Sheets",
        "Turnarounds",
        "Orthographics",
        "3D Assets",
        "Textures",
        "Materials",
        "UI Kits",
        "Icon Sets",
        "VFX Packages",
        "Presentation Decks",
        "In-Engine Scenes",
        "Look Dev",
        "Lighting Passes",
        "Polish Passes",
        "Portfolio Pieces",
        "Visual Clarity",
        "Production Quality",
        "Readability",
        "Strong Art Direction",
        "Consistent Style",
        "Optimized Assets",
        "Faster Integration",
        "Player Immersion",
        "Clear Feedback",
        "High Visual Fidelity",
        "Efficient Pipeline",
        "Lower Rework",
        "Better Presentation",
        "Shippable Content",
        "Polish",
        "Creativity",
        "Communication",
        "Collaboration",
        "Attention to Detail",
        "Ownership",
        "Adaptability",
        "Critique Handling",
        "Presentation Skills",
        "Problem Solving",
        "Organization",
        "Artistic Judgment",
        "Empathy"
      ],
      "totalTerms": 154
    },
    "data_scientist_game": {
      "displayName": "Data Scientist",
      "roleFamily": "data",
      "weights": {
        "coreTitles": 5.0,
        "altTitles": 4.0,
        "gameSignals": 5.0,
        "toolsAndTech": 5.0,
        "enginesPlatforms": 2.0,
        "methodologies": 5.0,
        "deliverables": 4.0,
        "outcomes": 5.0,
        "softSignals": 2.0
      },
      "categories": {
        "coreTitles": [
          "Data Scientist",
          "Game Data Scientist",
          "Product Data Scientist",
          "Analytics Scientist",
          "Decision Scientist",
          "Machine Learning Scientist",
          "Player Insights Scientist",
          "Research Scientist",
          "Monetization Data Scientist",
          "Live Ops Data Scientist"
        ],
        "altTitles": [
          "Quantitative Analyst",
          "Experimentation Scientist",
          "Behavioral Data Scientist",
          "Applied Scientist",
          "Analytics Manager",
          "Senior Data Scientist",
          "Player Behavior Analyst",
          "Economy Scientist",
          "Growth Scientist",
          "ML Scientist"
        ],
        "gameSignals": [
          "Player Behavior",
          "Retention Modeling",
          "Churn Prediction",
          "LTV Modeling",
          "Player Segmentation",
          "Cohort Analysis",
          "Funnel Analysis",
          "Engagement Metrics",
          "Session Analysis",
          "Monetization Analytics",
          "Economy Analytics",
          "Matchmaking Analytics",
          "Fraud Detection",
          "Cheat Detection",
          "Recommender Systems",
          "Offer Optimization",
          "A/B Testing",
          "Experimentation",
          "Live Ops Analytics",
          "Telemetry",
          "Event Taxonomy",
          "Instrumentation",
          "DAU",
          "MAU",
          "WAU",
          "ARPU",
          "ARPPU",
          "ARPDAU",
          "Conversion",
          "Payer Conversion",
          "Battle Pass",
          "F2P",
          "North Star Metrics",
          "Feature Adoption",
          "Skill Rating",
          "Player Journey",
          "Player Sentiment",
          "Survey Analysis"
        ],
        "toolsAndTech": [
          "Python",
          "R",
          "SQL",
          "Pandas",
          "NumPy",
          "SciPy",
          "scikit-learn",
          "XGBoost",
          "LightGBM",
          "PyTorch",
          "TensorFlow",
          "Jupyter",
          "Databricks",
          "BigQuery",
          "Snowflake",
          "Spark",
          "PySpark",
          "dbt",
          "Airflow",
          "Tableau",
          "Looker",
          "Power BI",
          "Matplotlib",
          "Plotly",
          "Seaborn",
          "Git",
          "Docker",
          "APIs",
          "Feature Stores",
          "MLflow",
          "Experiment Tracking",
          "Bayesian Methods"
        ],
        "enginesPlatforms": [
          "PC",
          "Console",
          "Mobile",
          "Cross-Platform",
          "Live Service"
        ],
        "methodologies": [
          "Machine Learning",
          "Predictive Modeling",
          "Classification",
          "Regression",
          "Clustering",
          "Recommendation Systems",
          "Hypothesis Testing",
          "Statistical Significance",
          "Confidence Intervals",
          "Causal Inference",
          "Sampling",
          "Feature Engineering",
          "Model Evaluation",
          "Cross Validation",
          "Precision",
          "Recall",
          "F1 Score",
          "ROC AUC",
          "Time Series",
          "Forecasting",
          "Anomaly Detection",
          "Model Monitoring",
          "Drift Detection",
          "MLOps",
          "Data Storytelling"
        ],
        "deliverables": [
          "Dashboards",
          "Experiment Readouts",
          "Model Artifacts",
          "Feature Importance Analyses",
          "Segmentation Schemes",
          "Forecasts",
          "Insight Decks",
          "Metric Definitions",
          "Decision Memos",
          "Model Validation Reports",
          "KPI Trees",
          "Player Insight Reports",
          "Telemetry Specs",
          "Notebook Analyses",
          "Recommendations"
        ],
        "outcomes": [
          "Better Retention",
          "Revenue Lift",
          "Experiment Velocity",
          "Smarter Live Ops Decisions",
          "Player Understanding",
          "Improved Conversion",
          "Reduced Churn",
          "Healthier Economy",
          "Better Match Quality",
          "Fraud Reduction",
          "Faster Insights",
          "Model Accuracy",
          "Business Impact",
          "Actionable Analytics",
          "Data-Informed Decisions"
        ],
        "softSignals": [
          "Communication",
          "Stakeholder Management",
          "Curiosity",
          "Analytical Thinking",
          "Problem Solving",
          "Ownership",
          "Storytelling",
          "Collaboration",
          "Business Acumen",
          "Player Empathy",
          "Experiment Mindset",
          "Adaptability"
        ]
      },
      "allTerms": [
        "Data Scientist",
        "Game Data Scientist",
        "Product Data Scientist",
        "Analytics Scientist",
        "Decision Scientist",
        "Machine Learning Scientist",
        "Player Insights Scientist",
        "Research Scientist",
        "Monetization Data Scientist",
        "Live Ops Data Scientist",
        "Quantitative Analyst",
        "Experimentation Scientist",
        "Behavioral Data Scientist",
        "Applied Scientist",
        "Analytics Manager",
        "Senior Data Scientist",
        "Player Behavior Analyst",
        "Economy Scientist",
        "Growth Scientist",
        "ML Scientist",
        "Player Behavior",
        "Retention Modeling",
        "Churn Prediction",
        "LTV Modeling",
        "Player Segmentation",
        "Cohort Analysis",
        "Funnel Analysis",
        "Engagement Metrics",
        "Session Analysis",
        "Monetization Analytics",
        "Economy Analytics",
        "Matchmaking Analytics",
        "Fraud Detection",
        "Cheat Detection",
        "Recommender Systems",
        "Offer Optimization",
        "A/B Testing",
        "Experimentation",
        "Live Ops Analytics",
        "Telemetry",
        "Event Taxonomy",
        "Instrumentation",
        "DAU",
        "MAU",
        "WAU",
        "ARPU",
        "ARPPU",
        "ARPDAU",
        "Conversion",
        "Payer Conversion",
        "Battle Pass",
        "F2P",
        "North Star Metrics",
        "Feature Adoption",
        "Skill Rating",
        "Player Journey",
        "Player Sentiment",
        "Survey Analysis",
        "Python",
        "R",
        "SQL",
        "Pandas",
        "NumPy",
        "SciPy",
        "scikit-learn",
        "XGBoost",
        "LightGBM",
        "PyTorch",
        "TensorFlow",
        "Jupyter",
        "Databricks",
        "BigQuery",
        "Snowflake",
        "Spark",
        "PySpark",
        "dbt",
        "Airflow",
        "Tableau",
        "Looker",
        "Power BI",
        "Matplotlib",
        "Plotly",
        "Seaborn",
        "Git",
        "Docker",
        "APIs",
        "Feature Stores",
        "MLflow",
        "Experiment Tracking",
        "Bayesian Methods",
        "PC",
        "Console",
        "Mobile",
        "Cross-Platform",
        "Live Service",
        "Machine Learning",
        "Predictive Modeling",
        "Classification",
        "Regression",
        "Clustering",
        "Recommendation Systems",
        "Hypothesis Testing",
        "Statistical Significance",
        "Confidence Intervals",
        "Causal Inference",
        "Sampling",
        "Feature Engineering",
        "Model Evaluation",
        "Cross Validation",
        "Precision",
        "Recall",
        "F1 Score",
        "ROC AUC",
        "Time Series",
        "Forecasting",
        "Anomaly Detection",
        "Model Monitoring",
        "Drift Detection",
        "MLOps",
        "Data Storytelling",
        "Dashboards",
        "Experiment Readouts",
        "Model Artifacts",
        "Feature Importance Analyses",
        "Segmentation Schemes",
        "Forecasts",
        "Insight Decks",
        "Metric Definitions",
        "Decision Memos",
        "Model Validation Reports",
        "KPI Trees",
        "Player Insight Reports",
        "Telemetry Specs",
        "Notebook Analyses",
        "Recommendations",
        "Better Retention",
        "Revenue Lift",
        "Experiment Velocity",
        "Smarter Live Ops Decisions",
        "Player Understanding",
        "Improved Conversion",
        "Reduced Churn",
        "Healthier Economy",
        "Better Match Quality",
        "Fraud Reduction",
        "Faster Insights",
        "Model Accuracy",
        "Business Impact",
        "Actionable Analytics",
        "Data-Informed Decisions",
        "Communication",
        "Stakeholder Management",
        "Curiosity",
        "Analytical Thinking",
        "Problem Solving",
        "Ownership",
        "Storytelling",
        "Collaboration",
        "Business Acumen",
        "Player Empathy",
        "Experiment Mindset",
        "Adaptability"
      ],
      "totalTerms": 162
    },
    "data_engineer_game": {
      "displayName": "Data Engineer",
      "roleFamily": "data",
      "weights": {
        "coreTitles": 5.0,
        "altTitles": 4.0,
        "gameSignals": 4.5,
        "toolsAndTech": 5.0,
        "enginesPlatforms": 2.0,
        "methodologies": 4.5,
        "deliverables": 4.0,
        "outcomes": 4.5,
        "softSignals": 1.5
      },
      "categories": {
        "coreTitles": [
          "Data Engineer",
          "Game Data Engineer",
          "Analytics Engineer",
          "Big Data Engineer",
          "ETL Engineer",
          "ELT Engineer",
          "Platform Data Engineer",
          "Data Platform Engineer",
          "Streaming Data Engineer",
          "Machine Learning Data Engineer"
        ],
        "altTitles": [
          "Senior Data Engineer",
          "Data Integration Engineer",
          "Pipeline Engineer",
          "Warehouse Engineer",
          "Lakehouse Engineer",
          "Analytics Platform Engineer",
          "DataOps Engineer",
          "BI Engineer",
          "Telemetry Data Engineer",
          "Cloud Data Engineer"
        ],
        "gameSignals": [
          "Telemetry Pipelines",
          "Event Ingestion",
          "Player Analytics",
          "Live Ops Data",
          "Experimentation Support",
          "A/B Test Data",
          "Economy Data",
          "Monetization Data",
          "Session Data",
          "Crash Data",
          "Gameplay Events",
          "User Acquisition Data",
          "Attribution Data",
          "Feature Stores",
          "ML Data Pipelines",
          "Real-Time Data",
          "Shipped Titles",
          "Backfills",
          "Reprocessing",
          "Data Contracts",
          "Event Taxonomy",
          "Player Account Data",
          "Commerce Data"
        ],
        "toolsAndTech": [
          "Python",
          "SQL",
          "Scala",
          "Java",
          "Spark",
          "PySpark",
          "Airflow",
          "Dagster",
          "dbt",
          "Kafka",
          "Kinesis",
          "Pub/Sub",
          "Databricks",
          "BigQuery",
          "Snowflake",
          "Redshift",
          "S3",
          "GCS",
          "ADLS",
          "Parquet",
          "Avro",
          "ORC",
          "PostgreSQL",
          "MySQL",
          "MongoDB",
          "Redis",
          "Cassandra",
          "ClickHouse",
          "Trino",
          "Presto",
          "Docker",
          "Kubernetes",
          "Terraform",
          "Git",
          "GitHub Actions",
          "CI/CD",
          "REST APIs",
          "gRPC",
          "Microservices",
          "Cloud",
          "AWS",
          "GCP",
          "Azure",
          "Glue",
          "Iceberg",
          "Delta Lake"
        ],
        "enginesPlatforms": [
          "PC",
          "Console",
          "Mobile",
          "Cross-Platform"
        ],
        "methodologies": [
          "ETL",
          "ELT",
          "Batch Processing",
          "Streaming",
          "Data Modeling",
          "Dimensional Modeling",
          "Star Schema",
          "Snowflake Schema",
          "Data Warehousing",
          "Lakehouse",
          "Data Quality",
          "Data Validation",
          "Observability",
          "Monitoring",
          "Alerting",
          "Lineage",
          "Metadata",
          "Catalog",
          "Data Governance",
          "Access Control",
          "IAM",
          "Security",
          "PII Handling",
          "Compliance",
          "Partitioning",
          "Clustering",
          "Indexing",
          "Performance Tuning",
          "Orchestration",
          "Scheduling",
          "Reliability Engineering",
          "Fault Tolerance",
          "SLA",
          "SLO",
          "Incident Response"
        ],
        "deliverables": [
          "Pipelines",
          "Data Models",
          "Warehouse Tables",
          "Semantic Layers",
          "ETL Jobs",
          "Streaming Jobs",
          "Data Quality Checks",
          "Orchestration DAGs",
          "Runbooks",
          "Monitoring Dashboards",
          "Backfill Plans",
          "Schema Definitions",
          "Event Specs",
          "Documentation",
          "Access Policies",
          "Incident Reviews"
        ],
        "outcomes": [
          "Reliable Data",
          "Scalable Pipelines",
          "Faster Analytics",
          "Trusted Metrics",
          "Lower Latency",
          "Better Experimentation",
          "Operational Stability",
          "Data Accessibility",
          "Cost Efficiency",
          "Data Freshness",
          "High Throughput",
          "Lower Failure Rates",
          "Faster Backfills",
          "Better Governance",
          "ML Readiness"
        ],
        "softSignals": [
          "Problem Solving",
          "Communication",
          "Collaboration",
          "Ownership",
          "Execution",
          "Systems Thinking",
          "Adaptability",
          "Reliability",
          "Stakeholder Partnership"
        ]
      },
      "allTerms": [
        "Data Engineer",
        "Game Data Engineer",
        "Analytics Engineer",
        "Big Data Engineer",
        "ETL Engineer",
        "ELT Engineer",
        "Platform Data Engineer",
        "Data Platform Engineer",
        "Streaming Data Engineer",
        "Machine Learning Data Engineer",
        "Senior Data Engineer",
        "Data Integration Engineer",
        "Pipeline Engineer",
        "Warehouse Engineer",
        "Lakehouse Engineer",
        "Analytics Platform Engineer",
        "DataOps Engineer",
        "BI Engineer",
        "Telemetry Data Engineer",
        "Cloud Data Engineer",
        "Telemetry Pipelines",
        "Event Ingestion",
        "Player Analytics",
        "Live Ops Data",
        "Experimentation Support",
        "A/B Test Data",
        "Economy Data",
        "Monetization Data",
        "Session Data",
        "Crash Data",
        "Gameplay Events",
        "User Acquisition Data",
        "Attribution Data",
        "Feature Stores",
        "ML Data Pipelines",
        "Real-Time Data",
        "Shipped Titles",
        "Backfills",
        "Reprocessing",
        "Data Contracts",
        "Event Taxonomy",
        "Player Account Data",
        "Commerce Data",
        "Python",
        "SQL",
        "Scala",
        "Java",
        "Spark",
        "PySpark",
        "Airflow",
        "Dagster",
        "dbt",
        "Kafka",
        "Kinesis",
        "Pub/Sub",
        "Databricks",
        "BigQuery",
        "Snowflake",
        "Redshift",
        "S3",
        "GCS",
        "ADLS",
        "Parquet",
        "Avro",
        "ORC",
        "PostgreSQL",
        "MySQL",
        "MongoDB",
        "Redis",
        "Cassandra",
        "ClickHouse",
        "Trino",
        "Presto",
        "Docker",
        "Kubernetes",
        "Terraform",
        "Git",
        "GitHub Actions",
        "CI/CD",
        "REST APIs",
        "gRPC",
        "Microservices",
        "Cloud",
        "AWS",
        "GCP",
        "Azure",
        "Glue",
        "Iceberg",
        "Delta Lake",
        "PC",
        "Console",
        "Mobile",
        "Cross-Platform",
        "ETL",
        "ELT",
        "Batch Processing",
        "Streaming",
        "Data Modeling",
        "Dimensional Modeling",
        "Star Schema",
        "Snowflake Schema",
        "Data Warehousing",
        "Lakehouse",
        "Data Quality",
        "Data Validation",
        "Observability",
        "Monitoring",
        "Alerting",
        "Lineage",
        "Metadata",
        "Catalog",
        "Data Governance",
        "Access Control",
        "IAM",
        "Security",
        "PII Handling",
        "Compliance",
        "Partitioning",
        "Clustering",
        "Indexing",
        "Performance Tuning",
        "Orchestration",
        "Scheduling",
        "Reliability Engineering",
        "Fault Tolerance",
        "SLA",
        "SLO",
        "Incident Response",
        "Pipelines",
        "Data Models",
        "Warehouse Tables",
        "Semantic Layers",
        "ETL Jobs",
        "Streaming Jobs",
        "Data Quality Checks",
        "Orchestration DAGs",
        "Runbooks",
        "Monitoring Dashboards",
        "Backfill Plans",
        "Schema Definitions",
        "Event Specs",
        "Documentation",
        "Access Policies",
        "Incident Reviews",
        "Reliable Data",
        "Scalable Pipelines",
        "Faster Analytics",
        "Trusted Metrics",
        "Lower Latency",
        "Better Experimentation",
        "Operational Stability",
        "Data Accessibility",
        "Cost Efficiency",
        "Data Freshness",
        "High Throughput",
        "Lower Failure Rates",
        "Faster Backfills",
        "Better Governance",
        "ML Readiness",
        "Problem Solving",
        "Communication",
        "Collaboration",
        "Ownership",
        "Execution",
        "Systems Thinking",
        "Adaptability",
        "Reliability",
        "Stakeholder Partnership"
      ],
      "totalTerms": 168
    }
  }
} as const;

export type GameRoleKey = keyof typeof GAME_ROLES_KEYWORDS.roles;
export default GAME_ROLES_KEYWORDS;
